# Site settings
title: Andrew Jones
email: atjones0011@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer working in New York City's startup scene.
  My focus is on datastores and developing data intensive distributed systems.
baseurl: ""
url: "http://atjones.co"
twitter_username: atjones0011
github_username:  atjones0011

# Build settings
markdown: kramdown
